// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficerService.Data;

#nullable disable

namespace OfficerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008113811_UpdateMasterRolesColumnLengths")]
    partial class UpdateMasterRolesColumnLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficerService.Models.MasterRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Deactivated_On");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<DateTime?>("ReactivatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Reactivated_On");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Role_Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Updated_By");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_Date");

                    b.HasKey("RoleId");

                    b.ToTable("Master_Roles");
                });

            modelBuilder.Entity("OfficerService.Models.OfficerDetails", b =>
                {
                    b.Property<int>("OfficerDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Officer_Detail_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerDetailId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Officer_Email_Address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Active");

                    b.Property<string>("OfficerDesignationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Officer_Designation_Id");

                    b.Property<string>("OfficerLoginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Login_id");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Officer_Name");

                    b.Property<string>("OfficerNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Officer_Number");

                    b.Property<string>("OfficerTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Officer_Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_Date");

                    b.HasKey("OfficerDetailId");

                    b.HasIndex("OfficerLoginId")
                        .IsUnique();

                    b.ToTable("Officer_Details");
                });

            modelBuilder.Entity("OfficerService.Models.OfficerRegistration", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Officer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("Location_id");

                    b.Property<int>("LocationType")
                        .HasColumnType("int")
                        .HasColumnName("Location_Type");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Login_Id");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mobile_No");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Updated_By");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_Date");

                    b.HasKey("OfficerId");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Officer_Registration");
                });

            modelBuilder.Entity("OfficerService.Models.OfficerDetails", b =>
                {
                    b.HasOne("OfficerService.Models.OfficerRegistration", "OfficerRegistration")
                        .WithOne("OfficerDetails")
                        .HasForeignKey("OfficerService.Models.OfficerDetails", "OfficerLoginId")
                        .HasPrincipalKey("OfficerService.Models.OfficerRegistration", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficerRegistration");
                });

            modelBuilder.Entity("OfficerService.Models.OfficerRegistration", b =>
                {
                    b.HasOne("OfficerService.Models.MasterRoles", "Role")
                        .WithMany("OfficerRegistrations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OfficerService.Models.MasterRoles", b =>
                {
                    b.Navigation("OfficerRegistrations");
                });

            modelBuilder.Entity("OfficerService.Models.OfficerRegistration", b =>
                {
                    b.Navigation("OfficerDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
