// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeciesService.Data;

#nullable disable

namespace SpeciesService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250918091039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpeciesService.Models.ForestProduce", b =>
                {
                    b.Property<int>("ForestProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Forest_Produce_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForestProduceId"));

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("QuantityType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Quantity_Type");

                    b.Property<string>("RequiresLog")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Requires_Log");

                    b.Property<string>("WeightType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Weight_Type");

                    b.HasKey("ForestProduceId");

                    b.ToTable("Forest_Produce");
                });

            modelBuilder.Entity("SpeciesService.Models.MasterSpecies", b =>
                {
                    b.Property<int>("SpeciesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpeciesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesID"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("SpeciesID");

                    b.ToTable("Master_Species");
                });
#pragma warning restore 612, 618
        }
    }
}
