// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeciesService.Data;

#nullable disable

namespace SpeciesService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpeciesService.Models.ForestProduce", b =>
                {
                    b.Property<int>("ForestProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Forest_Produce_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForestProduceId"));

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("QuantityType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Quantity_Type");

                    b.Property<string>("RequiresLog")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Requires_Log");

                    b.Property<string>("WeightType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Weight_Type");

                    b.HasKey("ForestProduceId");

                    b.ToTable("Forest_Produce");
                });

            modelBuilder.Entity("SpeciesService.Models.MasterSpecies", b =>
                {
                    b.Property<int>("SpeciesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpeciesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesID"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("SpeciesID");

                    b.ToTable("Master_Species");
                });

            modelBuilder.Entity("SpeciesService.Models.SpeciesExempted", b =>
                {
                    b.Property<int>("ExemptedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Exempted_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExemptedId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<int?>("DistCode")
                        .HasColumnType("int")
                        .HasColumnName("DIST_CODE");

                    b.Property<int?>("ExemptORNotExempt")
                        .HasColumnType("int")
                        .HasColumnName("ExemptORNotExempt");

                    b.Property<int?>("ProduceSpeciesID")
                        .HasColumnType("int")
                        .HasColumnName("ProduceSpeciesID");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("int")
                        .HasColumnName("Species_Id");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("State_Id");

                    b.HasKey("ExemptedId");

                    b.HasIndex("ProduceSpeciesID");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Species_Exempted");
                });

            modelBuilder.Entity("SpeciesService.Models.SpeciesExempted", b =>
                {
                    b.HasOne("SpeciesService.Models.ForestProduce", "ForestProduce")
                        .WithMany("SpeciesExemptedList")
                        .HasForeignKey("ProduceSpeciesID");

                    b.HasOne("SpeciesService.Models.MasterSpecies", "MasterSpecies")
                        .WithMany("SpeciesExemptions")
                        .HasForeignKey("SpeciesId");

                    b.Navigation("ForestProduce");

                    b.Navigation("MasterSpecies");
                });

            modelBuilder.Entity("SpeciesService.Models.ForestProduce", b =>
                {
                    b.Navigation("SpeciesExemptedList");
                });

            modelBuilder.Entity("SpeciesService.Models.MasterSpecies", b =>
                {
                    b.Navigation("SpeciesExemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
