// <auto-generated />
using System;
using AuthenticationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthenticationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821094416_AuthenticationDbSetup")]
    partial class AuthenticationDbSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthenticationService.Models.ApplicantPersonalDetails", b =>
                {
                    b.Property<int>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Details_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailsId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<int?>("CircleId")
                        .HasColumnType("int")
                        .HasColumnName("Circle_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("Division_id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("IDNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ID_Number");

                    b.Property<string>("IDProof")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ID_Proof");

                    b.Property<string>("IDUpload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ID_Upload");

                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Login_id");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Modification_Date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pin_Code");

                    b.Property<int?>("RangeId")
                        .HasColumnType("int")
                        .HasColumnName("Range_Id");

                    b.Property<string>("SourceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source_Type");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("State_Id");

                    b.Property<int?>("SubDivisionId")
                        .HasColumnType("int")
                        .HasColumnName("Sub_division_id");

                    b.HasKey("DetailsId");

                    b.ToTable("Applicant_Personal_Details");
                });

            modelBuilder.Entity("AuthenticationService.Models.MasterRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Registration_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email_id");

                    b.Property<string>("IsVerified")
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Is_Verified");

                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Login_Id");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mobile_No");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("NameTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name_Title");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("RegistrationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Registration_Type");

                    b.HasKey("RegistrationId");

                    b.ToTable("Master_Registration");
                });

            modelBuilder.Entity("AuthenticationService.Models.VerifyOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Application_Id");

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasColumnName("Attempt");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mobile_No");

                    b.Property<string>("Otp")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("OTP");

                    b.Property<int?>("OtpCasesId")
                        .HasColumnType("int")
                        .HasColumnName("OTP_Cases_Id");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_Date");

                    b.HasKey("Id");

                    b.ToTable("Verify_Otp");
                });
#pragma warning restore 612, 618
        }
    }
}
