// <auto-generated />
using System;
using MasterAdminService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterAdminService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterAdminService.Models.Circle", b =>
                {
                    b.Property<int>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Circle_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CircleId"));

                    b.Property<string>("CircleName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Circle_Name");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("State_Id");

                    b.Property<int?>("TPValidity")
                        .HasColumnType("int")
                        .HasColumnName("TP_Validity");

                    b.HasKey("CircleId");

                    b.HasIndex("StateId");

                    b.ToTable("Circle", (string)null);
                });

            modelBuilder.Entity("MasterAdminService.Models.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Division_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<int?>("CircleId")
                        .HasColumnType("int")
                        .HasColumnName("Circle_Id");

                    b.Property<int?>("DistCode")
                        .HasColumnType("int")
                        .HasColumnName("DIST_CODE");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Division_Name");

                    b.Property<int?>("TPValidity")
                        .HasColumnType("int")
                        .HasColumnName("TP_Validity");

                    b.HasKey("DivisionId");

                    b.HasIndex("CircleId");

                    b.ToTable("Division", (string)null);
                });

            modelBuilder.Entity("MasterAdminService.Models.Range", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Range_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeId"));

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("Division_Id");

                    b.Property<int?>("DivisionId1")
                        .HasColumnType("int");

                    b.Property<string>("RangeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Range_Name");

                    b.Property<int?>("SubDivId")
                        .HasColumnType("int")
                        .HasColumnName("Sub_Div_Id");

                    b.Property<int?>("TPValidity")
                        .HasColumnType("int")
                        .HasColumnName("TP_Validity");

                    b.Property<string>("UploadedHammer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Uploaded_Hammer");

                    b.HasKey("RangeId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("DivisionId1");

                    b.HasIndex("SubDivId");

                    b.ToTable("Range", (string)null);
                });

            modelBuilder.Entity("MasterAdminService.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("State_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("Language_Id");

                    b.Property<string>("LocalRule")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Local_Rule");

                    b.Property<string>("Lock")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Lock");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("Region_Id");

                    b.Property<string>("RequiredField")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Required_Field");

                    b.Property<int?>("STCode")
                        .HasColumnType("int")
                        .HasColumnName("ST_CODE");

                    b.Property<string>("Show")
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Show");

                    b.Property<string>("SpeciesDOC")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Species_DOC");

                    b.Property<string>("StatURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("StatURL");

                    b.Property<string>("StateCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("State_Code");

                    b.Property<string>("StateName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("State_Name");

                    b.Property<int?>("TPValidity")
                        .HasColumnType("int")
                        .HasColumnName("TP_Validity");

                    b.HasKey("StateId");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("MasterAdminService.Models.SubDivision", b =>
                {
                    b.Property<int>("SubDivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Sub_Div_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubDivId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_date");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("Division_Id");

                    b.Property<int?>("DivisionId1")
                        .HasColumnType("int");

                    b.Property<string>("SubDivName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Sub_Div_Name");

                    b.HasKey("SubDivId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("DivisionId1");

                    b.ToTable("Sub_Division", (string)null);
                });

            modelBuilder.Entity("MasterAdminService.Models.Circle", b =>
                {
                    b.HasOne("MasterAdminService.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("State");
                });

            modelBuilder.Entity("MasterAdminService.Models.Division", b =>
                {
                    b.HasOne("MasterAdminService.Models.Circle", "Circle")
                        .WithMany("Divisions")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("MasterAdminService.Models.Range", b =>
                {
                    b.HasOne("MasterAdminService.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterAdminService.Models.Division", null)
                        .WithMany("Ranges")
                        .HasForeignKey("DivisionId1");

                    b.HasOne("MasterAdminService.Models.SubDivision", "SubDivision")
                        .WithMany("Ranges")
                        .HasForeignKey("SubDivId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Division");

                    b.Navigation("SubDivision");
                });

            modelBuilder.Entity("MasterAdminService.Models.SubDivision", b =>
                {
                    b.HasOne("MasterAdminService.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasterAdminService.Models.Division", null)
                        .WithMany("SubDivisions")
                        .HasForeignKey("DivisionId1");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("MasterAdminService.Models.Circle", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("MasterAdminService.Models.Division", b =>
                {
                    b.Navigation("Ranges");

                    b.Navigation("SubDivisions");
                });

            modelBuilder.Entity("MasterAdminService.Models.SubDivision", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
